---
title: "Introduction to CausalInvestData"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to CausalInvestData}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(CausalInvestData)
```

## Overview

`CausalInvestData` provides simulated datasets for causal inference in institutional investment management.

## Dataset: `fund_performance`

```{r}
head(fund_performance)
```

## Propensity Score Matching

```{r}
library(MatchIt)
m.out <- matchit(treatment ~ market_return + alpha + beta, data = fund_performance)
summary(m.out)
```

---

## Dataset: `portfolio_allocations`

```{r}
head(read.csv(system.file("data", "portfolio_allocations.csv", package = "CausalInvestData")))
```

## Dataset: `client_behavior`

```{r}
head(read.csv(system.file("data", "client_behavior.csv", package = "CausalInvestData")))
```

## Dataset: `macro_shocks`

```{r}
head(read.csv(system.file("data", "macro_shocks.csv", package = "CausalInvestData")))
```
